[WIP] Add sites to build in github actions
OpenHistoricalMap/ohm-deploy pull request #200
Opened 2023-01-24 00:21 UTC by Rub21

I have started some actions to build sites in this repository and push to s3.

cc. @batpad

2023-01-25 09:19 UTC, geohacker requested changes

2023-01-25 09:19 UTC, geohacker commented on .github/workflows/nominatim.yaml
> +      - name: Setup git
@Rub21 I dont think we should use git config and git clone this way. We use the official github action for checkout https://github.com/actions/checkout

2023-01-25 09:21 UTC, geohacker requested changes

2023-01-25 09:21 UTC, geohacker commented on .github/workflows/nominatim.yaml
> +          git clone https://github.com/OpenHistoricalMap/nominatim-ui.git
Again, we shouldn't do `git clone` just rely on an existing action module.

2023-01-25 09:43 UTC, batpad commented
Yup - @Rub21 this looks great to me - would just be great to switch to using the github action module and clearly indicate the repo and git tag / commit to use from that repo. And then I think we could make similar actions for all the frontend repositories as per https://github.com/OpenHistoricalMap/issues/issues/477

2023-01-26 20:21 UTC, Rub21 commented
@batpad @geohacker I am going to merge this PR to staging , in order to see that is working fine, there, locally it is working good!

2023-01-26 20:21 UTC, merged